openstackcontroller:
    image: cloudnautique/kolla-base:mitaka
    privileged: true
    net: host
    labels:
        io.rancher.scheduler.affinity:host_label: openstack=controller
        io.rancher.container.start_once: "true"
    volumes:
        - /run:/host/run
        - /proc:/host/proc
        - /:/host
        - /var/run/docker.sock:/var/run/docker.sock
    command: bash -x /run.sh
    environment:
        OPENSTACK_INTERNAL_VIP_ADDRESS: "${openstack_internal_vip_address}"
        OPENSTACK_API_INTERFACE: "${openstack_api_interface}"
        OPENSTACK_NEUTRON_INTERFACE: "${openstack_neutron_interface}"
