.catalog:
    name: Openstack
    version: 2.0.1-rancher1
    questions:
        - variable: "openstack_internal_vip_address"
          type: string
          required: true
          description: |
              This is the address you want your services to bind to.
          label: "Internal VIP address"
        - variable: "openstack_api_interface"
          type: string
          required: true
          description: |
              This is the network interface the VIP will live on.
          label: "VIP Interface"
        - variable: "openstack_neutron_interface"
          type: string
          required: true
          description: |
              This is the network interface for Neutron network
          label: "Neutron Network Interface"
        - variable: "ansible_private_ssh_key"
          type: textfield
          required: true
          description: |
              private SSH key to use for Ansible
          label: Private SSH Key
        - variable: "ansible_public_ssh_key"
          type: textfield
          required: true
          description: |
              public SSH key to use for Ansible
          label: Public SSH Key
